### ISSUE TITLE
Inspector Bug in Godot 3.5.stable official

### ISSUE THREAD

**Issue by SebastianAtWork** [Daylily-Zeleen/HierarchicalFiniteStateMachine#1]
Hi,
really cool plugin, but unfortunately i found a critical bug in the inspector of the hfsm editor : 
![image](https://user-images.githubusercontent.com/19798013/190897247-01b4a147-1189-46e4-948b-cd3b3bae45bc.png)

Changing the transition type doesnt do anything and if i click somewhere else and back on the transition, its back to delay.

Also btw. What are the differences between trial and payed version?

**Comment by Daylily-Zeleen** [comment]
> Hi, really cool plugin, but unfortunately i found a critical bug in the inspector of the hfsm editor : ![image](https://user-images.githubusercontent.com/19798013/190897247-01b4a147-1189-46e4-948b-cd3b3bae45bc.png)
> 
> Changing the transition type doesnt do anything and if i click somewhere else and back on the transition, its back to delay.
> 
> Also btw. What are the differences between trial and payed version?

Thank's for your using my plugin and bug report.
I already fix this bug, please download the latest version.

The full version have saveral features:
1. Suppoets `GDscript` and `C#` script to implement the logic of transitions. ( like using script to implement the logic of states.
2. A very simple debugger.
3. Some advance methods for hfsm:
    set_entry_state(state_name : String , fsm_path : Array =["root"])
    set_exit_state(state_name : String , fsm_path : Array =["root"])
    set_unique_exit_state(state_name : String , fsm_path : Array =["root"])
    set_normal_state(state_name : String , fsm_path : =["root"])
    force_entry(fsm_path : Array = ["root"] , entry_state_name : String = "")
    force_exit(fsm_path : Array =["root"])
    force_transit(target_state : String , fsm_path : =["root"])


As you can see, these features are not important, and the trail version is enough for common usage. To buy the full version is just to support my open source development. 

Please check the [document](https://github.com/Daylily-Zeleen/HierarchicalFiniteStateMachine/blob/main/Document_en.md) for more imformation if you need.

**Comment by SebastianAtWork** [comment]
Super, thanks for the fast help :) I think you forgot to update the version for the plugin, it still is labeled at 0.8 in the editor. Otherwise works

**Comment by Daylily-Zeleen** [comment]
> Super, thanks for the fast help :) I think you forgot to update the version for the plugin, it still is labeled at 0.8 in the editor. Otherwise works

Please download from Github page directly, Asset Library is reviewing the new version.
