### ISSUE TITLE
godot4.1无法启用插件

### ISSUE THREAD

**Issue by Nebulafalls** [Daylily-Zeleen/HierarchicalFiniteStateMachine#3]
![image](https://github.com/Daylily-Zeleen/HierarchicalFiniteStateMachine/assets/53670448/b54e6096-54a7-43ce-b6a8-a0b18bcbab20)

**Comment by Daylily-Zeleen** [comment]
这是3.5的插件

4.1用的大概会这两周内会发布测试版

我将关闭这个issue，如果你在3.5以上的3.x版本使用中遇到问题，欢迎你再次提交issue。
